name: "CodeCheck"

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: java

      - name: Build with Maven
        run: mvn install

      - uses: actions/upload-artifact@v2
        name: Upload Artifact
        with:
          name: SecuritySK.jar
          path: target/SecuritySK*.jar
